services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres_mvc

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb-dev

    ports:
      - 5432:5432